version: "3.8"

networks: 
  base-bridge:
      driver: bridge

services: 
### PHP-FPM ########################################  
    php7.1-fpm:
        build:
          context: ./php-fpm
          args:
            - X_PHP_VERSION=7.1
            - INSTALL_XDEBUG=${PHP71_FPM_INSTALL_XDEBUG}
            - INSTALL_SWOOLE=${PHP71_FPM_INSTALL_SWOOLE}
            - INSTALL_WKHTMLTOPDF=${PHP71_FPM_INSTALL_WKHTMLTOPDF}
        volumes:
        - ./php-fpm/php7.1.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        tty: true
        ports:
        - "${industrious_API_PORT}:${industrious_API_CONTAINER_PORT}"
        expose:
        - "9000"
        networks:
        - base-bridge  
    php7.3-fpm:
        build:
          context: ./php-fpm
          args:
            - X_PHP_VERSION=7.3
            - INSTALL_XDEBUG=${PHP73_FPM_INSTALL_XDEBUG}
            - INSTALL_SWOOLE=${PHP73_FPM_INSTALL_SWOOLE}
            - INSTALL_WKHTMLTOPDF=${PHP73_FPM_INSTALL_WKHTMLTOPDF}
        volumes:
        - ./php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        tty: true
        expose:
        - "9000"
        networks:
        - base-bridge 
    php7.4-fpm:
        build:
          context: ./php-fpm
          args:
            - X_PHP_VERSION=7.4
            - INSTALL_XDEBUG=${PHP74_FPM_INSTALL_XDEBUG}
            - INSTALL_SWOOLE=${PHP74_FPM_INSTALL_SWOOLE}
            - INSTALL_WKHTMLTOPDF=${PHP74_FPM_INSTALL_WKHTMLTOPDF}
        volumes:
        - ./php-fpm/php7.4.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        tty: true
        expose:
        - "9000"
        networks:
        - base-bridge     

### Redis ########################################            
    redis:
        build: ./redis
        volumes:
        - ${DATA_PATH_HOST}/redis:/data
        ports:
        - "${REDIS_PORT}:6379"
        networks:
        - base-bridge  

### Nginx(tengine) ########################################         
    nginx:  
        build: ./nginx
        volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        ports:
        - "80:80"
        - "443:443"
        networks:
        - base-bridge
        depends_on:
        - php7.1-fpm
        - php7.3-fpm 

### Rabbitmq ########################################          
    rabbitmq:
        build: ./rabbitmq
        ports:
          - "${RABBITMQ_NODE_HOST_PORT}:5672"
          - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
          - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
        privileged: true
        environment:
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        volumes:
          - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq/mnesia
        networks:
        - base-bridge
        
### ElasticSearch ########################################
    elasticsearch:
      build:
        context: ./elasticsearch
        args:
          - ELK_VERSION=${ELK_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/elasticsearch:/usr/share/elasticsearch/data
      environment:
        - cluster.name=pdocker-cluster
        - node.name=pdocker-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - cluster.initial_master_nodes=pdocker-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
      networks:
        - base-bridge

### Logstash ##############################################
    #logstash

### Kibana ##############################################
    kibana:
      build:
        context: ./kibana
        args:
          - ELK_VERSION=${ELK_VERSION}
      ports:
        - "${KIBANA_HTTP_PORT}:5601"
      depends_on:
        - elasticsearch
      networks:
        - base-bridge
