version: "3.8"

networks: 
  base-bridge:
      driver: bridge
volumes:
  mongodata:
    #external: true
    name:  mongodata

services: 
### Redis ########################################            
    redis:
        #image: ${DOCKER_USER}/redis
        build: ./redis
        volumes:
        - ${DATA_PATH_HOST}/redis:/data
        ports:
        - "${REDIS_PORT}:6379"
        networks:
        - base-bridge  

### Rabbitmq ########################################          
    rabbitmq:
        #image: ${DOCKER_USER}/rabbitmq
        build: ./rabbitmq
        ports:
          - "${RABBITMQ_NODE_HOST_PORT}:5672"
          - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
          - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
        privileged: true
        environment:
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        volumes:
          - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq/mnesia
        networks:
        - base-bridge   

### MongoDB ##############################################
    mongo:
      #image: ${DOCKER_USER}/mongo
      build: ./mongo
      ports:
        - "${MONGODB_PORT}:27017"
      volumes:
        - mongodata:/data/db
        #- ${DATA_PATH_HOST}/mongo_config:/data/configdb
      networks:
        - base-bridge   

### Nginx(tengine) ########################################         
    nginx:
      #image: ${DOCKER_USER}/nginx
      build: ./nginx
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "80:80"
        - "81:81"
        - "443:443"
        - "8443:8443"
      networks:
        - base-bridge

### ElasticSearch ########################################
    elasticsearch:
      #image: ${DOCKER_USER}/elasticsearch
      build:
        context: ./elasticsearch
        args:
          - ELK_VERSION=${ELK_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/elasticsearch:/usr/share/elasticsearch/data
      environment:
        - cluster.name=docker-cluster
        - node.name=docker-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - cluster.initial_master_nodes=docker-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
      networks:
        - base-bridge

### Logstash ##############################################
    #logstash

### Kibana ##############################################
    kibana:
      #image: ${DOCKER_USER}/kibana
      build:
        context: ./kibana
        args:
          - ELK_VERSION=${ELK_VERSION}
      volumes:
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      ports:
        - "${KIBANA_HTTP_PORT}:5601"
      depends_on:
        - elasticsearch
      networks:
        - base-bridge

################################################       
### PHP ######################################## 
#######PHP7.1-FPM 
    php7.1-fpm:
        build:
          context: ./php-fpm
          args:
            - X_PHP_VERSION=7.1
            - INSTALL_WKHTMLTOPDF=${PHP71_FPM_INSTALL_WKHTMLTOPDF}
        volumes:
        - ./php-fpm/php7.1.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ./logs/php7.1-fpm/:/var/log/php7.1-fpm
        tty: true
        privileged: true
        expose:
        - "9000"
        networks:
        - base-bridge  
#######PHP7.3-FPM  
    php7.3-fpm:
        build:
          context: ./php-fpm
          args:
            - X_PHP_VERSION=7.3
            - INSTALL_WKHTMLTOPDF=${PHP73_FPM_INSTALL_WKHTMLTOPDF}
        volumes:
        - ./php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
        - ./php-fpm/php7.3-fpm.conf:/usr/local/etc/php-fpm.d/php7.3-fpm.conf
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${PHP73_FPM_LOG_PATH}:/var/log/php7.3-fpm
        tty: true
        expose:
        - "9000"
        ports:
        - "${PHP73_FPM_TMP_PORT}:7777"
        cap_add:
        - SYS_PTRACE
        networks:
        - base-bridge          
#######PHP7.4-FPM    
    php7.4-fpm:
        build:
          context: ./php-fpm
          args:
            - X_PHP_VERSION=7.4
            - INSTALL_WKHTMLTOPDF=${PHP74_FPM_INSTALL_WKHTMLTOPDF}
        volumes:
        - ./php-fpm/php7.4.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${PHP74_FPM_LOG_PATH}:/var/log/php7.4-fpm
        tty: true
        expose:
        - "9000"
        ports:
        - "${PHP74_FPM_TMP_PORT}:7777"
        cap_add:
        - SYS_PTRACE
        networks:
        - base-bridge  
### PHP-CLI ########################################  
#######PHP7.1-CLI
    php7.1-cli:
        build:
          context: ./php-cli
          args:
            - X_PHP_VERSION=7.1
            - INSTALL_WKHTMLTOPDF=${PHP71_CLI_INSTALL_WKHTMLTOPDF}
        volumes:
        - ./php-cli/php7.1.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        tty: true
        ports:
        - "${PHP71_CLI_TMP_PORT}:7777" 
        networks:
        - base-bridge          
#######PHP7.4-CLI
    php7.4-cli:
        build:
          context: ./php-cli
          args:
            - X_PHP_VERSION=7.4
            - INSTALL_WKHTMLTOPDF=${PHP74_CLI_INSTALL_WKHTMLTOPDF}
        volumes:
        - ./php-cli/php7.4.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        tty: true
        ports:
        - "${PHP74_CLI_TMP_PORT}:7777"
        - "9501:9501"
        networks:
        - base-bridge          